#!/usr/bin/env bash

if [ $# -lt 1 ]; then
    echo "Usage: $0 <component-name> [component-name ...]"
    exit 1
fi

# ____________________________________________________________________

tab="  "

function fillVueFile () {
    echo -n >> $vue_file "\
<template>
${tab}<div>
${tab}</div>
</template>

<script lang=\"ts\">
export default {
${tab}name: '${1}',
${tab}data() {
${tab}${tab}return {
${tab}${tab}};
${tab}},
${tab}methods: {
${tab}},
${tab}components: {
${tab}},
}
</script>

<style scoped src=\"./$(basename ${css_file})\">
</style>
"
}

function fillCssFile () {
    touch ${css_file}
}

function createComponent () {
    # $1 == component-name
    lowercase=$(echo "${1}" | awk '{ print tolower($0) }')
    targetDir="./src/components/${1}"
    css_file="${targetDir}/${1}.css"
    vue_file="${targetDir}/${1}.vue"

    mkdir -p ${targetDir}
    fillVueFile ${1}
    fillCssFile
}

function main () {
	for component_name in ${@}; do
		echo "Creating '$component_name' component..."
        createComponent $component_name
	done
}

main $@
