FROM node:16-alpine3.11

WORKDIR /app_backend

# Install dependencies required for project
RUN npm i -g @nestjs/cli

EXPOSE 443

ENTRYPOINT npm install && npm run start:prod

# command: docker attach backend_app
