FROM node:16-alpine3.11

WORKDIR /app_frontend

# Vue.JS
RUN npm i -g vue @vue/cli @vue/cli-service

EXPOSE 3030

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3030

# Dependencies from package.json and start the server
ENTRYPOINT npm install && npm run dev
