FROM node:16-alpine3.11

WORKDIR /app_frontend

# Install depencies required for project
RUN npm i -g @nestjs/cli

# dependency for VueJS
RUN npm i vue -g @vue/cli @vue/cli-service

# dependency for axios
RUN npm i axios


EXPOSE 8080

# CMD [ "sh" ]
CMD sleep infinity
