FROM node:16-alpine3.11

WORKDIR /app_frontend

# Vue.JS
RUN npm i vue -g @vue/cli @vue/cli-service

# Axios
RUN npm i axios

EXPOSE 8080

# Dependencies from package.json and start the server
ENTRYPOINT npm install && npm run serve
